name = "central"
license = "MIT"
description = "Edward Tufte-esque Hugo theme."
homepage = "https://github.com/irfansharif/central"
tags = ["blog"]
features = ["responsive", "blog"]
min_version = 0.18

[author]
  name = "Irfan Sharif"
  homepage = "https://irfansharif.io/"

# vim: ts=2 sw=2 et ft=conf
