# Hugo variables

baseurl = "https://irfansharif.io/central/"
canonifyURLs = "true"
languageCode = "en-us"
title = "Vivamus dui Arcu"
theme = "central"
[markup]
  defaultMarkdownHandler = "blackfriday"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

# Theme variables
[params]
  author = "Leonardo da Vinci"
  description = "Cras rutrum eros at lectus eleifend aliquam."

# vim: ts=2 sw=2 et ft=conf
